# Save this content as config.yaml
properties:
  configurationVersion: 0.2.0
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installVSCode
      directives:
        description: "Install Visual Studio Code"
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installgit 
      directives:
        description: "Install Git"
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installtypora
      directives:
        description: "Install Typora"
      settings:
        id: appmakes.Typora
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installpython
      directives:
        description: "Install Python 3.13"
      settings:
        id: Python.Python.3.13
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: install7zip
      directives:
        description: "Install 7-Zip"
      settings:
        id: 7zip.7zip
        source: winget
  
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installsnagit
      directives:
        description: "Install Snagit"
      settings:
        id: TechSmith.Snagit.2024
        source: winget
  
  - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installwindsurf
      directives:
        description: "Install WindSurf"
      settings:
        id: Codeium.Windsurf
        source: winget